.TH PLOVER 1 
.\" 
.\"
.SH NAME
plover \- stenography input method for X11
.SH SYNOPSIS
.B plover
.br
.SH "DESCRIPTION"
Plover is an input method for X11.
It is a free open source program intended to bring realtime stenographic technology not just to stenographers, but also to hackers, hobbyists, accessibility mavens, and all-around speed demons.

.SH OVERVIEW
In stenography, keystroke chords are used to type entire words at a time,
rather than typing letter-by-letter as with qwerty or dvorak keyboards.

.SH KNOWN BUGS
This manual page needs a lot of work.

.SH DEBIAN 
This manpage was written by
.B Thomas Thurman
<
.I thomas@thurman.org.uk
> for the Debian GNU/Linux operating system, but
may be freely used by others.
